version: '3'

services:
  netobserv-ebpf-agent:
    image:  quay.io/shachee/netobserv-ebpf-agent:main-amd64
    container_name: netobserv-ebpf-agent
    restart: always
    environment:
      - PCA_SERVER_PORT=57012
      - FLOWS_TARGET_HOST=127.0.0.1
      - ENABLE_PCA=true
      - PCA_FILTER=udp,53
      - LOG_LEVEL=debug
      - AGENT_IP=127.0.0.1
    cap_add:
        - CAP_BPF
        - CAP_PERFMON
        - CAP_NET_ADMIN
        - CAP_SYS_RESOURCE
    volumes:
        - /sys/kernel/debug:/sys/kernel/debug:rw
        - /sys:/sys:rw
    privileged: true
    user: root
    network_mode: "host"

  kafka:
    image: 'pano-kafka:latest'
    container_name: kafka
    # ports:
    # - 9092:9092
    # - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    network_mode: "host"
        
  zeek:
    image: "pano-zeek:5.0.9"
    container_name: zeek
    depends_on: 
      - kafka
    volumes:
     - ./zeek/logs/:/usr/local/zeek/logs:rw
    command: /usr/local/zeek/bin/zeek -D -B plugin-Zeek-PcapOverTcp -C -e 'redef LogAscii::use_json = T;' -i pcapovertcp::127.0.0.1:57012  /usr/local/zeek/share/zeek/site/local.zeek
    network_mode: "host"

  flowlogs-pipeline:
    image: 'pano-flowlogs-pipeline:latest'
    container_name: flowlogs-pipeline
    depends_on: 
      - kafka
    # ports:
    # - 9102:9102
    command:
      - --config=/app/pano-kafka-dns.yaml
    network_mode: "host"

  prometheus:
    image: 'pano-prometheus'
    container_name: prometheus 
    # ports: 
    #   - 9090 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    # ports:
    #  - 3000:3000
    user: '0'
    volumes:
      - '$PWD/grafana/data:/var/lib/grafana'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin #TODO
      - GF_SECURITY_ADMIN_PASSWORD=admin #TODO
    network_mode: "host"

  dnsperf1:
    image: pano-dnsperf
    container_name: dnsperf1
    depends_on:
      - netobserv-ebpf-agent
      - kafka
      - zeek
      - flowlogs-pipeline
      - prometheus
      - grafana
    environment:
      - DNS_SERVER_ADDR=8.8.8.8
      - MAX_TEST_SECONDS=3000
    network_mode: host
  
  dnsperf2:
    image: pano-dnsperf
    container_name: dnsperf2
    depends_on:
      - netobserv-ebpf-agent
      - kafka
      - zeek
      - flowlogs-pipeline
      - prometheus
      - grafana
    environment:
      - DNS_SERVER_ADDR=9.0.0.1
      - MAX_TEST_SECONDS=3000
    network_mode: host
