{
 "title": "PANO DNS Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cumulative Total of DNS Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pano_dns_query_count" }
   ]
  },
  {
   "title": "Rate of DNS Queries",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pano_dns_query_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Average Response Time (seconds)",
   "type": "timeseries",
   "description": "Response Time of DNS response in ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pano_dns_rtt_avg" }
   ]
  },
  {
   "title": "DNS Response Time Histogram",
   "type": "timeseries",
   "description": "Histogram of Response Time (.99, .9, .75, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(pano_dns_rtt_histogram_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "DNS Return Code Rate",
   "type": "timeseries",
   "description": "Return code (NOERROR, NXDOMAIN, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pano_dns_rcode_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "DNS Return Code Percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pano_dns_rcode_total" }
   ]
  },
  {
   "title": "DNS Query Type  Rate",
   "type": "timeseries",
   "description": "Types of Queries (A, AAAA, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pano_dns_qtype_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "DNS Query Type Percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pano_dns_qtype_total" }
   ]
  }
 ]
}