log-level: error
metricsSettings:
  port: 9102
  suppressGoMetrics: true
  prefix: pano_dns_
pipeline:
  - name: ingest
# query
  - name: aggregate_query
    follows: ingest
  - name: filter_query
    follows: aggregate_query
  - name: prom_query
    follows: filter_query
# qtype
  - name: aggregate_qtype
    follows: ingest
  - name: filter_qtype
    follows: aggregate_qtype
  - name: prom_qtype
    follows: filter_qtype
# rcode
  - name: aggregate_rcode
    follows: ingest
  - name: filter_rcode
    follows: aggregate_rcode
  - name: prom_rcode
    follows: filter_rcode
# rtt_avg
  - name: aggregate_rtt_avg
    follows: ingest
  - name: prom_rtt_avg
    follows: aggregate_rtt_avg
# rtt_hist
  - name: aggregate_rtt_hist
    follows: ingest
  - name: prom_rtt_hist
    follows: aggregate_rtt_hist
parameters:
  - name: ingest
    ingest:
      type: kafka
      kafka:
        brokers: ["localhost:9092"]
        topic: dns
        decoder:
          type: json
# query
  - name: aggregate_query
    extract:
      type: aggregates
      aggregates:
        rules:
        - name: query_count
          groupByKeys:
            - query
          operationType: count
          operationKey: query
  - name: filter_query
    transform:
      type: filter
      filter:
        rules:
        - input: query
          type: remove_entry_if_doesnt_exist
  - name: prom_query
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: query_total
          type: counter
          valueKey: recent_op_value
          labels:
            - query
# qtype
  - name: aggregate_qtype
    extract:
      type: aggregates
      aggregates:
        rules:
        - name: qtype_count
          groupByKeys:
            - qtype_name
          operationType: count
          operationKey: qtype
  - name: filter_qtype
    transform:
      type: filter
      filter:
        rules:
        - input: qtype_name
          type: remove_entry_if_doesnt_exist
  - name: prom_qtype
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: qtype_total
          type: counter
          valueKey: recent_op_value
          labels:
            - qtype_name
# rcode
  - name: aggregate_rcode
    extract:
      type: aggregates
      aggregates:
        rules:
        - name: rcode_count
          groupByKeys:
            - rcode_name
          operationType: count
          operationKey: rcode
  - name: filter_rcode
    transform:
      type: filter
      filter:
        rules:
        - input: rcode_name
          type: remove_entry_if_doesnt_exist
  - name: prom_rcode
    encode:
      type: prom
      prom:
       prefix: pano_dns_
       metrics:
       - name: rcode_total
         type: counter
         valueKey: recent_op_value
         labels:
           - rcode_name
# rtt_avg
  - name: aggregate_rtt_avg
    extract: 
      type: aggregates
      aggregates: 
        rules:
        - name: aggr_rtt_avg
          groupByKeys:
            - id_resp_h
          operationType: avg
          operationKey: rtt
  - name: prom_rtt_avg
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: rtt_avg
          type: gauge
          labels:
            - id_resp_h
          valueKey: recent_op_value
# rtt_hist
  - name: aggregate_rtt_hist
    extract:
      type: aggregates
      aggregates:
        rules:
        - name: aggr_rtt_hist
          operationType: raw_values
          operationKey: rtt
  - name: prom_rtt_hist
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: rtt_histogram
          type: agg_histogram
          valueKey: recent_raw_values
          buckets:
           - 0.00001
           - 0.0001
           - 0.001
           - 0.01
           - 0.10
           - 1.00
           - 10.00
