log-level: error
metricsSettings:
  port: 9102
  suppressGoMetrics: true
  prefix: pano_dns_
pipeline:
  - name: ingest_kafka
  - name: aggregate_values
    follows: ingest_kafka
  - name: encode_prom
    follows: aggregate_values
parameters:
  - name: ingest_kafka
    ingest:
      type: kafka
      kafka:
        brokers: ["localhost:9092"]
        topic: dns
        decoder:
          type: json
  - name: aggregate_values
    extract: 
      type: aggregates
      aggregates: 
        rules:
        - name: aggr_rtt_avg
          operationType: avg
          operationKey: rtt
        - name: aggr_rtt_hist
          operationType: raw_values
          operationKey: rtt
        - name: qtype_count
          groupByKeys:
            - qtype_name
          operationType: count
          operationKey: qtype
        - name: query_count
          groupByKeys:
            - query
          operationType: count
          operationKey: query
        - name: rcode_count
          groupByKeys:
            - rcode_name
          operationType: count
          operationKey: rcode
  - name: encode_prom
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: rcode_total
          type: counter
          valueKey: recent_op_value
          labels:
            - rcode_name
        - name: query_count
          type: counter
        - name: query_total
          type: counter
          valueKey: recent_op_value
          labels:
           - query
        - name: qtype_total
          type: counter
          valueKey: recent_op_value
          labels:
            - qtype_name
        - name: rtt_histogram
          type: agg_histogram
          valueKey: recent_raw_values
          buckets:
           - 0.00001
           - 0.0001
           - 0.001
           - 0.01
           - 0.10
           - 1.00
           - 10.00
        - name: rtt_avg
          type: gauge
          valueKey: recent_op_value
          filter: {key: name, value: aggr_rtt_avg}
        
