version: '3'

networks:
  pano-network:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - pano-network
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
        
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    networks:
      - pano-network
    ports:
      - 9094:9094
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin #TODO
      - GF_SECURITY_ADMIN_PASSWORD=password #TODO

  prometheus:
    image: prom/prometheus:v2.30.3 # TODO which version
    container_name: prometheus
    networks:
      - pano-network
    ports:
      - 9095:9095
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always 

  pano-netobserv-agent:
    image:  netobserv-ebpf-agent/bin/netobserv-ebpf-agent
    container_name: netobserv-ebpf-agent
    networks:
      - pano-network
    ports: 
      - 57102:57102
    volumes:
      - :./netobserv-ebpf-agent/bin # TODO Fix location of agent
    restart: always

  zeek:
    image: "zeek:v5.0.7"
    container_name: zeek
    networks:
      - pano-network
    volumes:
     - ./zeek/logs/:/usr/local/zeek/logs:rw
    command: /usr/local/zeek/bin/zeek -C -i pcapovertcp::127.0.0.1:57102  /usr/local/zeek/share/zeek/site/local.zeek

