version: '3'

services:
  netobserv-ebpf-agent:
    image:  quay.io/enahum/netobserv-ebpf-agent:main
    container_name: netobserv-ebpf-agent
    ports:
      - 57012:57012
    restart: always
    environment:
      - FLOWS_TARGET_PORT=57012
      - FLOWS_TARGET_HOST=127.0.0.1
      - ENABLE_PANO=true

  kafka:
    image: 'pano-kafka:latest'
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
        
  zeek:
    image: "pano-zeek-debug:5.0.9"
    container_name: zeek
    depends_on: 
      - kafka
    volumes:
     - ./zeek/logs/:/usr/local/zeek/logs:rw
    command: /usr/local/zeek/bin/zeek -D -B plugin-Zeek-PcapOverTcp -C -e 'redef LogAscii::use_json = T;' -i pcapovertcp::netobserv-ebpf-agent:57012  /usr/local/zeek/share/zeek/site/local.zeek

  flowlogs-pipeline:
    image: 'pano-flowlogs-pipeline:latest'
    container_name: flowlogs-pipeline
    depends_on: 
      - kafka
    ports:
      - 9102:9102
    command:
      - --config=/app/docker-pano-kafka-dns.yaml
